// Generated by jextract

package io.github.doblon8.openpnp.capture.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang = c:
 * struct {
 *     uint32_t width;
 *     uint32_t height;
 *     uint32_t fourcc;
 *     uint32_t fps;
 *     uint32_t bpp;
 * }
 *}
 */
public class CapFormatInfo {

    CapFormatInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            openpnp_capture.C_INT.withName("width"),
            openpnp_capture.C_INT.withName("height"),
            openpnp_capture.C_INT.withName("fourcc"),
            openpnp_capture.C_INT.withName("fps"),
            openpnp_capture.C_INT.withName("bpp")
    ).withName("$anon$96:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt width$LAYOUT = (OfInt) $LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * uint32_t width
     *}
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * uint32_t width
     *}
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * uint32_t width
     *}
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * uint32_t width
     *}
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt) $LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * uint32_t height
     *}
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * uint32_t height
     *}
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * uint32_t height
     *}
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * uint32_t height
     *}
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt fourcc$LAYOUT = (OfInt) $LAYOUT.select(groupElement("fourcc"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * uint32_t fourcc
     *}
     */
    public static final OfInt fourcc$layout() {
        return fourcc$LAYOUT;
    }

    private static final long fourcc$OFFSET = $LAYOUT.byteOffset(groupElement("fourcc"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * uint32_t fourcc
     *}
     */
    public static final long fourcc$offset() {
        return fourcc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * uint32_t fourcc
     *}
     */
    public static int fourcc(MemorySegment struct) {
        return struct.get(fourcc$LAYOUT, fourcc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * uint32_t fourcc
     *}
     */
    public static void fourcc(MemorySegment struct, int fieldValue) {
        struct.set(fourcc$LAYOUT, fourcc$OFFSET, fieldValue);
    }

    private static final OfInt fps$LAYOUT = (OfInt) $LAYOUT.select(groupElement("fps"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * uint32_t fps
     *}
     */
    public static final OfInt fps$layout() {
        return fps$LAYOUT;
    }

    private static final long fps$OFFSET = $LAYOUT.byteOffset(groupElement("fps"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * uint32_t fps
     *}
     */
    public static final long fps$offset() {
        return fps$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * uint32_t fps
     *}
     */
    public static int fps(MemorySegment struct) {
        return struct.get(fps$LAYOUT, fps$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * uint32_t fps
     *}
     */
    public static void fps(MemorySegment struct, int fieldValue) {
        struct.set(fps$LAYOUT, fps$OFFSET, fieldValue);
    }

    private static final OfInt bpp$LAYOUT = (OfInt) $LAYOUT.select(groupElement("bpp"));

    /**
     * Layout for field:
     * {@snippet lang = c:
     * uint32_t bpp
     *}
     */
    public static final OfInt bpp$layout() {
        return bpp$LAYOUT;
    }

    private static final long bpp$OFFSET = $LAYOUT.byteOffset(groupElement("bpp"));

    /**
     * Offset for field:
     * {@snippet lang = c:
     * uint32_t bpp
     *}
     */
    public static final long bpp$offset() {
        return bpp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang = c:
     * uint32_t bpp
     *}
     */
    public static int bpp(MemorySegment struct) {
        return struct.get(bpp$LAYOUT, bpp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang = c:
     * uint32_t bpp
     *}
     */
    public static void bpp(MemorySegment struct, int fieldValue) {
        struct.set(bpp$LAYOUT, bpp$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() {
        return layout().byteSize();
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

