package io.github.doblon8.openpnp.capture;

import io.github.doblon8.openpnp.capture.bindings.CapCustomLogFunc;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.util.function.BiConsumer;

import static io.github.doblon8.openpnp.capture.bindings.openpnp_capture.*;

public class OpenPnpCapture implements AutoCloseable {

    private final CaptureContext context;
    private static final Arena arena = Arena.ofAuto();

    public OpenPnpCapture() {
        this.context = new CaptureContext();
    }

    /**
     * Get the number of capture devices on the system.
     * <p>
     * Note: this can change dynamically due to the plugging and unplugging of USB devices.
     *
     * @return the number of capture devices found.
     */
    public int getDeviceCount() {
        return Cap_getDeviceCount(context.getSegment());
    }

    /**
     * Get the name of a capture device.
     * <p>
     * If a device with the given index does not exist, null is returned.
     *
     * @param index the device index of the capture device.
     * @return the name of the capture device, or null if no device with the given index exists.
     */
    public String getDeviceName(int index) {
        MemorySegment stringPointer = Cap_getDeviceName(context.getSegment(), index);
        return stringPointer.equals(MemorySegment.NULL) ? null : stringPointer.getString(0);
    }

    /**
     * Return the version of the library as a string.
     * <p>
     * In addition to a version number, this should contain information on the platform;
     * e.g. Win32/Win64/Linux32/Linux64/OSX etc., whether or not it is a release or debug build, and the build date.
     *
     * @return the version of the library as a string.
     */
    public static String getLibraryVersion() {
        return Cap_getLibraryVersion().getString(0);
    }

    /**
     * Set the logging level.
     *
     * @param level the logging level to set. Log messages with a level below this will be ignored.
     */
    public static void setLogLevel(LogLevel level) {
        Cap_setLogLevel(level.ordinal());
    }

    /**
     * Install a custom callback for logging function
     *
     * @param logFunction a function that takes a LogLevel and a String message,
     *                    which will be called for each log message generated by the library.
     */
    public static void installCustomLogFunction(BiConsumer<LogLevel, String> logFunction) {
        MemorySegment functionPointer = CapCustomLogFunc.allocate((level, stringPointer) ->
                logFunction.accept(LogLevel.values()[level], stringPointer.getString(0)), arena);
        Cap_installCustomLogFunction(functionPointer);
    }

    @Override
    public void close() throws CaptureException {
        context.close();
    }
}
